### ISSUE TITLE
Segementation violation in freshly set up writefreely 0.13.1

### ISSUE THREAD

**Issue by hllizi** [writefreely/writefreely#567]
I am trying to set up a fresh instance of writefreely v0.13.1 on NixOS (but I could reproduce the reported error in an alpine container with the standard packages from the alpine repository).

The configuration step (`writefreely config start`) worked as expected, generating the attached config file:
 
```
[server]
hidden_host          = 
port                 = 8000
bind                 = localhost
tls_cert_path        = 
tls_key_path         = 
autocert             = false
templates_parent_dir = 
static_parent_dir    = 
pages_parent_dir     = 
keys_parent_dir      = 
hash_seed            = 
gopher_port          = 0

[database]
type     = sqlite3
filename = writefreely.db
username = 
password = 
database = 
host     = localhost
port     = 3306
tls      = false

[app]
site_name             = Pleasures of writery
site_description      = 
host                  = http://localhost:9876
theme                 = write
editor                = 
disable_js            = false
webfonts              = true
landing               = 
simple_nav            = false
wf_modesty            = false
chorus                = false
forest                = false
disable_drafts        = false
single_user           = true
open_registration     = false
open_deletion         = false
min_username_len      = 3
max_blogs             = 1
federation            = true
public_stats          = false
monetization          = false
notes_only            = false
private               = true
local_timeline        = false
user_invites          = 
default_visibility    = 
update_checks         = false
disable_password_auth = false

[oauth.slack]
client_id          = 
client_secret      = 
team_id            = 
callback_proxy     = 
callback_proxy_api = 

[oauth.writeas]
client_id          = 
client_secret      = 
auth_location      = 
token_location     = 
inspect_location   = 
callback_proxy     = 
callback_proxy_api = 

[oauth.gitlab]
client_id          = 
client_secret      = 
host               = 
display_name       = 
callback_proxy     = 
callback_proxy_api = 

[oauth.gitea]
client_id          = 
client_secret      = 
host               = 
display_name       = 
callback_proxy     = 
callback_proxy_api = 

[oauth.generic]
client_id          = 
client_secret      = 
host               = 
display_name       = 
callback_proxy     = 
callback_proxy_api = 
token_endpoint     = 
inspect_endpoint   = 
auth_endpoint      = 
scope              = 
allow_disconnect   = false
map_user_id        = 
map_username       = 
map_display_name   = 
map_email          = 
```

`writefreely keys generate` also didn't complain. 

The templates directory was copied from this repository to the working directory (the most current version as well as the one for v0.13.1).

But trying to start writefreely with `writefreely serve` in the working directory generates the following output:

```
2022/06/10 08:37:32 Starting WriteFreely 0.13.1...
2022/06/10 08:37:32 Loading config.ini configuration...
2022/06/10 08:37:32 Loading templates...
2022/06/10 08:37:32 Loading pages...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x13aaf8f]

goroutine 1 [running]:
github.com/writefreely/writefreely.InitTemplates.func1(0x16baab6, 0x5, 0x0, 0x0, 0x17df160, 0xc00044ce10, 0x5, 0x1)
	github.com/writefreely/writefreely/templates.go:139 +0x2f
path/filepath.Walk(0x16baab6, 0x5, 0xc000207b08, 0x16baab6, 0x5)
	path/filepath/path.go:499 +0x7e
github.com/writefreely/writefreely.InitTemplates(0xc0000df680, 0xc00050a8a0, 0x0)
	github.com/writefreely/writefreely/templates.go:138 +0x25c
github.com/writefreely/writefreely.Initialize(0x17edcb8, 0xc00050a8a0, 0x0, 0xc000507c00, 0x1, 0x1)
	github.com/writefreely/writefreely/app.go:394 +0x6f
main.serveAction(0xc000449680, 0x1, 0x1)
	github.com/writefreely/writefreely/cmd/writefreely/web.go:34 +0x18e
github.com/urfave/cli/v2.(*Command).Run(0x20b1e40, 0xc0004495c0, 0x0, 0x0)
	github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x4dd
github.com/urfave/cli/v2.(*App).RunContext(0xc0000a3d40, 0x17ec7d0, 0xc00002c210, 0xc000020060, 0x2, 0x2, 0x0, 0x0)
	github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x810
github.com/urfave/cli/v2.(*App).Run(...)
	github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
	github.com/writefreely/writefreely/cmd/writefreely/main.go:118 +0x7cf
```

As remarked before, the problem could be reproduced with the alpine:latest image from the docker repositories, software installed in the canonical way using `apk add writefreely`and `apk add sqlite`. On nixos, the same error did also occur with a mysql backend. With the alpine container, I haven't tried yet.

**Comment by hllizi** [comment]
OK, closing this since the issue was a misunderstanding; the binary was missing its context in the work directory, except for the templates directory. Maybe the reasons for this misunderstanding might be of interest, so, briefly:

 * Running writefreely is advertised as "as easy as running a binary" or something along these lines.
 * At least Nixos and maybe also alpine only package the binary without context.
 * The error message I described in the ticket does not really make it obvious that the problem is missing context.

This resulted in my assumption that the binary required no further context. I should of course have doubted this when there was a complaint about the missing templates-directory. When I just now tried to install the binary as provided by you, I noticed that it came packaged with further files and this finally sunk it. (To be clear: these explanations are not meant to put any blame on you but just to elucidate where I went wrong. Though I'd suggest to make the error messages a little more perspicuous, exactly following the instructions you provided actually did the job.
